FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Padaria.AuthService/ Padaria.AuthService/
COPY Padaria.Shared/ Padaria.Shared/

RUN dotnet restore "Padaria.AuthService/Padaria.AuthService.csproj"


WORKDIR "/src/Padaria.AuthService"
RUN dotnet publish "Padaria.AuthService.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Padaria.AuthService.dll"]